Add systemd block for features in 242
cloudalchemy/ansible-blackbox-exporter pull request #48
Opened 2019-10-22 09:44 UTC by SuperQ

The system feature `RestrictSUIDSGID` didn't exist until 242. Add a
block around it to avoid logging noise.

```
systemd[1]: /etc/systemd/system/blackbox_exporter.service:30: Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
```

[patch]

2019-10-22 09:45 UTC, SuperQ commented
It looks like we've been not releasing this role in a while, there are 30+ changes in master since the last release.

2019-10-22 09:51 UTC, paulfantom commented
Systemd handles such cases by itself, issues a warning and just discards options that are not available. This provides systemd a mechanism for easy backwards compatibility and allows vendors to create systemd service files without needing to check if the option is available. That said we have a lot of cases where we don't check if the option we provide is available as it will create a huge maintenance toll. 

Does this option prevent blackbox_exporter from starting up?

---

Yes, we should do a release.

2019-10-24 13:31 UTC, paulfantom requested changes
I think this would create precedence which will complicate codebase. With this we would need to do the same for other systemd unit options. So just this part:
```
NoNewPrivileges=true
PrivateTmp=true
RemoveIPC=true
ProtectHome=true
MemoryDenyWriteExecute=true
LockPersonality=true
RestrictSUIDSGID=true
```

Would need to be turned into:
```
NoNewPrivileges=true
PrivateTmp=true
{% if blackbox_exporter_systemd_version | int >= 212 %}
RemoveIPC=true
{% endif %}
{% if blackbox_exporter_systemd_version | int >= 214 %}
ProtectHome=true
{% endif %}
{% if blackbox_exporter_systemd_version | int >= 231 %}
MemoryDenyWriteExecute=true
{% endif %}
{% if blackbox_exporter_systemd_version | int >= 235 %}
LockPersonality=true
{% endif %}
{% if blackbox_exporter_systemd_version | int >= 242 %}
RestrictSUIDSGID=true
{% endif %}
```

And even that is probably not complete.

2019-10-24 13:38 UTC, SuperQ commented
Hmm, ok, I just found the warnings annoying. :-)

2019-10-24 13:38 UTC, closed without merging